AttachmentSF/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import (
    login, 
    logout_then_login, 
    password_reset, 
    password_reset_done, 
    password_reset_confirm, 
    password_reset_complete
)

urlpatterns = [
    url(r'^PROA-Admin/', admin.site.urls),
    url(r'^sfMigrate/', include('apps.salesforceMigrate.urls', namespace='salesforceMigrate')),
    url(r'^contabilidad/', include('apps.contabilidad.urls', namespace='contabilidad')),
    url(r'^files/', include('db_file_storage.urls')),
    url(r'^', include('apps.usuario.urls', namespace='usuario')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, {
        'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'
        }, name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, {
        'template_name': 'registration/password_reset_done.html'
        }, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {
        'template_name': 'registration/password_reset_confirm.html'
        },name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {
        'template_name': 'registration/password_reset_complete.html'
        },name='password_reset_complete'),
]

apps/contabilidad/urls.py
# Django
from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Custom
from .forms import AttForm
from .models import Att
from .views import FilteredAttListView

urlpatterns = [
    url(r'^filter/$', FilteredAttListView.as_view(), name='FilterAtt'),
    url(
        r'^att/add/$',
        CreateView.as_view(
            model=Att,
            form_class=AttForm,
            template_name='att_form.html',
            success_url=reverse_lazy('contabilidad:conta')
            
        ),
        name='attAdd'
    ),
]

apps/salesforceMigrate/urls.py
# Django
from django.conf.urls import url, include

# Custom 
from .views import migrate, MultipleTables

urlpatterns = [
    url(r'^migrate/$', migrate, name='migrate'),
    url(r'^multiple/$', MultipleTables.as_view(), name='multitableview'),
]

apps/usuario/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.usuario.views import (
	#RegistroUsuario, 
	UserAPI,
	home
)

urlpatterns = [
	url(r'^$', login_required(home), name='home'),
	#url(r'^registrar', RegistroUsuario.as_view(), name="registrar"),
	url(r'^api', UserAPI.as_view(), name="api"),

]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}AttachmentSF {% endblock %}</title>
</head>
<body>
<!--div class="container"-->

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="{% url 'usuario:home' %}">AttachmentSF</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav navbar-right">
									{% if user.username == "admin" %}
										<li class="dropdown"><a href="{% url 'salesforceMigrate:multitableview' %}" onclick="pageTracker._link(this.href); return false;">Migrate</a>
									{% endif %}
									<li class="dropdown"><a href="{% url 'contabilidad:FilterAtt' %}" onclick="pageTracker._link(this.href); return false;">Contabilidad</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="{% url 'logout' %}">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>    

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
<!--/div-->
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>

templates/base/header.html
<header>Hola</header>